### ISSUE TITLE
Question: Detect italic additionally from font name?

### ISSUE THREAD

**Issue by kontur** [graphicore/specimenTools#16]
I had a closer look at the detection of the italic style in the FontsData. Due to a recent feedback I was wondering, if we should additionally try to detect if the word "Italic" is present in the font name, despite the correct fsSelection values not being set. This might be a case of users having to create proper files, but just throwing it up here as this came up with a user of my plugin that uses this library.

**Comment by kontur** [comment]
Added this in a preliminary way to [this branch](https://github.com/kontur/specimenTools/tree/italic)

**Comment by graphicore** [comment]
I guess this was closed with #17
