### ISSUE TITLE
[TypeTester] Adding more (optional) manipulation sliders to TypeTester

### ISSUE THREAD

**Issue by kontur** [graphicore/specimenTools#3]
It would be great to have additional sliders for:
* letter spacing
* line height
* (maybe:) word spacing

**Comment by graphicore** [comment]
Maybe we should have a generic way to make such sliders. like:

```html
<div class="type-tester__slider"
    data-target-property="font-size"
    data-unit="px"
    data-min="5"
    data-max="128"
    data-step="1"></div>
```

This case would manipulate the css `font-size` property. But I think this would suffice to create all the sliders you are asking for, so I think the effort would be well justified.

**Comment by kontur** [comment]
Not sure how close this is a) to what you had in mind or b) if it's implemented thoroughly enough, but it's a starting point.
Essentially `...__slider` classed elements get populated with a range input, and `..._label` classed elements with text, bound together by their shared `data-target-property`.
In particular I'm not sure if how I've handled deducting defaults from the slider is the best way to go.

Let me know what you think ;)

**Comment by graphicore** [comment]
When you do a PR I can post comments into the diffs.

**Comment by graphicore** [comment]
I just created #9
