### ISSUE TITLE
Woff2 support

### ISSUE THREAD

**Issue by elenaramirez** [graphicore/specimenTools#31]
Hello!

I'm using the specimen tool for a website but when i try to load woff2 files in the fontFiles array i got this error 
Can't load font fonts/EBGaramond12-Regular.woff2  with error: Error: Unsupported OpenType signature wOF2
Cannot read property 'familyIndex' of undefined.

Do you plan to add support for woff2 format?

Thank you!

**Comment by graphicore** [comment]
Hi, @elenaramirez, specimenTools uses [opentype.js](https://opentype.js.org) and depends on its support of font formats. There's an issue tracking the request for woff2 support: https://github.com/nodebox/opentype.js/issues/183 When opentype.js supports woff2, specimenTools should do so, too.
