### ISSUE TITLE
Flont interactive previewer?

### ISSUE THREAD

**Issue by davelab6** [graphicore/specimenTools#37]
Can https://github.com/chrissam42/Flont be used?

**Comment by graphicore** [comment]
It's trivial.

**Comment by graphicore** [comment]
There's actually one interesting feature, showing and selecting "alternative glyphs".

**Comment by graphicore** [comment]
> "alternative glyphs"

But it seems that needs the alternative glyphs to be encoded (PUA or so). I didn't read the whole code, would need more review to decide. Encouraging using PUA for a feature to work is the last thing I'd like to do.
