### ISSUE TITLE
example_main.js should probably not be in the lib folder

### ISSUE THREAD

**Issue by kontur** [graphicore/specimenTools#5]
Since it's a specific implementation example it should probably not be in the lib folder - what do you think?

**Comment by graphicore** [comment]
Maybe. Especially if we start to add more example implementations.

What about:

```
/examples/simple/main.js
/examples/simple/index.html
/examples/multiple/main.js
/examples/multiple/index.html
```

The `html` directory would also go away.

**Comment by kontur** [comment]
That seems to be a more intuitive structure 👍
