### ISSUE TITLE
How to approach a different rendering for FamilyChooser

### ISSUE THREAD

**Issue by kontur** [graphicore/specimenTools#7]
This is more of a question than an issue, but I was wondering if for the following case I should just write my own widget similar to FamilyChooser, or if this is something to customise:

Instead of every typeface (family) and weight supplied to one instance listed as buttons each, separated by typeface, I'd like a simple select with all the options.

Would you be interested in such a separate widget, or do you have ideas for how such a deviating layout could be implemented as customisation option of FamilyChooser?

**Comment by graphicore** [comment]
Have a look at [SimpleFileChooser](https://github.com/graphicore/specimenTools/blob/master/lib/widgets/SimpleFileChooser.js) We could pimp it to meet your needs.

**Comment by graphicore** [comment]
Also, I think I'll have to implement something as used in https://fonts.google.com/

![selection_117](https://cloud.githubusercontent.com/assets/393132/20057314/29047940-a4eb-11e6-9d92-891f14a71556.png)

Which is like a custom `<select>`

**Comment by kontur** [comment]
I made a simple [select dropdown alternative](https://github.com/kontur/specimenTools/commit/e0094b70545fde6ad8689ae9ae5d46567e4b9c4f) based on the SimpleFileChooser. For now no need to add it to the library, since it's not much added value. Could be used as a basis for this custom select idea, though.

**Comment by graphicore** [comment]
commented a bit.

**Comment by graphicore** [comment]
So, in the meantime I build one myself. I'll have to commit some changes to specimenTools, so that it would work with the master branch.

The main difference to your proposal is the use of `this._fontsData.getFontIndexesInFamilyOrder()` which should maybe become an option, because "FamilyOrder" will not always be possible. The definition of what's a family is generally rather google fonts specific.

I also included what I commented on in https://github.com/kontur/specimenTools/commit/e0094b70545fde6ad8689ae9ae5d46567e4b9c4f

**Comment by graphicore** [comment]
Oh, sorry, I see that I didn't put the link to the gist in here: https://gist.github.com/graphicore/1039071254e6bc9c020c8ab4f1cd50d9

You closed this, so what's your status on this? I think the `FontLister.js` is a good addition.

**Comment by kontur** [comment]
Sorry, this slipped past me as well. I can PR the FontLister, if you think it doesn't unnecessarily duplicate functionality with your approach. I've been using it in my Wordpress plugin already, so there's at least that use case ;)

**Comment by graphicore** [comment]
I updated my version in the meantime: https://gist.github.com/graphicore/1039071254e6bc9c020c8ab4f1cd50d9/revisions It now determines the order to display the fonts from the options. The default "load" order should be the same as in your approach.

I think what still differs is how the `option.textContent` is created.

What I prefer in my version is that it uses much less events and callbacks. Also, one biggie is that your's doesn't listen to ` this._pubSub.subscribe('activateFont', ...)`. Thus, it can't be switched by another tool emitting the 'activateFont' signal.

I'm not sure about your usage of `_prepareLoadHook` in combination with `this._selectContainer.enabled = true;` the `allFontsLoaded` event. I understand that this may be inherited from `SimpleFileChooser` but I'm not sure if we need it now in this case. Maybe in another iteration if we start to dynamically add/remove fonts?

**Comment by kontur** [comment]
Works for me 👍
